package org.roberthu.rs

import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.painter.BitmapPainter
import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.res.loadImageBitmap
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import androidx.compose.ui.window.rememberWindowState
import org.roberthu.rs.logging.ApplicationLogBootstrap
import org.roberthu.rs.presentation.BuildInfo
import org.slf4j.LoggerFactory

private val mainLogger = LoggerFactory.getLogger("org.roberthu.rs.MainKt")

private const val ApplicationIconResource = "app-icon.png"

/**
 * Loads the Compose Desktop window icon from the classpath.
 *
 * The asset is generated by `app/desktopApp/icons/generate_icons.py` into
 * `src/main/resources/app-icon.png`. Failures are logged and return `null`
 * so a missing icon never prevents startup.
 */
internal fun loadApplicationIcon(): Painter? {
    return try {
        val stream = ClassLoader.getSystemClassLoader().getResourceAsStream(ApplicationIconResource)
            ?: object {}.javaClass.getResourceAsStream("/$ApplicationIconResource")
        if (stream == null) {
            mainLogger.warn("Application icon resource '{}' was not found on the classpath", ApplicationIconResource)
            return null
        }
        stream.use { BitmapPainter(loadImageBitmap(it)) }
    } catch (error: Exception) {
        mainLogger.warn(
            "Failed to load application icon '{}': {}",
            ApplicationIconResource,
            error.message,
        )
        null
    }
}

fun main() {
    ApplicationLogBootstrap.initialize()

    val root = DesktopCompositionRoot()

    application {
        val appIcon = remember { loadApplicationIcon() }

        Window(
            onCloseRequest = {
                root.close()
                exitApplication()
            },
            title = "RedisStars",
            icon = appIcon,
            state = rememberWindowState(width = 1280.dp, height = 800.dp),
        ) {
            App(
                container = root.container,
                modifier = Modifier.fillMaxSize(),
                textFileImporter = awtTextFileImporter(),
                sshPrivateKeyPathPicker = awtSshPrivateKeyPathPicker(),
                runtimeLogSavePicker = awtRuntimeLogSavePicker(),
                buildInfo = BuildInfo(
                    version = System.getProperty("app.version") ?: "dev",
                    licenseName = "MIT License",
                ),
            )
        }
    }
}
